{
 "title": "Telegraf_MPXSIEM_Win",
 "description": "Core or All in One Configuration",
 "tags": [ "telegraf" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE system = 'windows'"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"win_disk\" WITH KEY = \"instance\""
   },
   {
    "name": "mpx_process",
    "label": "mpx_process",
    "query": "SHOW TAG VALUES FROM \"win_proc\" WITH KEY = \"instance\""
   },
   {
    "name": "network",
    "label": "Network Interface",
    "query": "SHOW TAG VALUES FROM \"win_net\" WITH KEY = \"instance\""
   },
   {
    "name": "siem_process",
    "label": "siem_process",
    "query": "SHOW TAG VALUES FROM \"win_proc\" WITH KEY = \"instance\""
   },
   {
    "name": "other_process",
    "label": "other_process",
    "query": "SHOW TAG VALUES FROM \"win_proc\" WITH KEY = \"instance\""
   }
  ]
 },
 "panels": [
  { "title": "INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT \"System_Up_Time\" FROM \"win_system\" WHERE \"host\" =~ /^$host$/ AND  $timeFilter",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" },
      { "condition": "AND", "key": "PT_project", "operator": "=~", "value": "/^$pt_project$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT last(\"Threads\") FROM \"win_system\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") FROM \"win_cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Available_Bytes\") FROM \"win_mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Drive $disk Free",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Percent_Free_Space\") FROM \"win_disk\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Disk_Read_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "C:" }
     ]
    }
   ]
  },
  { "title": "NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Bytes_Received_persec\") *8 AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Packets_Received_persec\") AS \"Packets Received / sec\", mean(\"Packets_Sent_persec\") AS \"Packets Sent / sec\" FROM \"win_net\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /$network$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SERVER UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$host: $col",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT last(\"Percent_Privileged_Time\") AS \"% Priviledged Time\", last(\"Percent_User_Time\") AS \"% User Time\", last(\"Percent_Interrupt_Time\") AS \"% Interrupt Time\", last(\"Percent_Idle_Time\") AS \"% Idle Time\", last(\"Percent_Processor_Time\") AS \"% Processor Time\" FROM \"win_cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Priviledged Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Available_Bytes\") as \"Available Bytes\", last(\"Cache_Bytes\") as \"Cache Bytes\", last(\"Free_&_Zero_Page_List_Bytes\") as \"Free_&_Zero_Page_List_Bytes\" FROM \"win_mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Page_Reads_persec\") as \"Page Reads persec\", last(\"Page_Writes_persec\") as \"Page Writes persec\" FROM \"win_mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Percent_Usage\") AS \"Swap percent usage\" FROM \"win_swap\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk $disk Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$disk: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"Percent_Free_Space\") AS \"% Free Space\" FROM \"win_disk\" WHERE \"instance\" =~ /^$disk$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$disk$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk $disk R/W Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$disk: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Disk_Read_Bytes_persec\") AS \"Disk_Read_Bytes_persec\", last(\"Disk_Write_Bytes_persec\") AS \"Disk_Write_Bytes_persec\" FROM \"win_disk\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk $disk Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$disk: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"Disk_Read_Bytes_persec\") AS \"Disk_Read_Bytes_persec\", last(\"Disk_Write_Bytes_persec\") AS \"Disk_Write_Bytes_persec\" FROM \"win_disk\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(0)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_sec/Transfer" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "transfer" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk $disk Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$disk:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"Avg._Disk_Read_Queue_Length\") AS \"Avg._Disk_Read_Queue_Length\", last(\"Avg._Disk_Write_Queue_Length\") AS \"Avg._Disk_Write_Queue_Length\" FROM \"win_disk\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(0)",
     "select": [
      [
       { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk $disk R/W IOps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$disk: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Disk_Reads_persec\") AS \"Disk_Reads_persec\", last(\"Disk_Writes_persec\") AS \"Disk_Writes_persec\" FROM \"win_disk\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk $disk % R/W Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$disk: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Percent_Disk_Read_Time\") AS \"% Disk Read Time\", last(\"Percent_Disk_Write_Time\") AS \"% Disk Write Time\" FROM \"win_disk\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "MPX SERVICES UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$mpx_process$/ AND $timeFilter GROUP BY time($interval), instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Working_Set_-_Private\") FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$mpx_process$/ AND $timeFilter GROUP BY time($interval), instance fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO bytes/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Read_Bytes_persec\") AS \"Read\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$mpx_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Write_Bytes_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$mpx_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO op/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Write_Operations_persec\") AS \"Read\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$mpx_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Read_Operations_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$mpx_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Handle Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Handle_Count\") as \"Handle Count\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$mpx_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SIEM SERVICES UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$siem_process$/ AND $timeFilter GROUP BY time($interval), instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Working_Set_-_Private\") FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$siem_process$/ AND $timeFilter GROUP BY time($interval), instance fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO bytes/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Read_Bytes_persec\") AS \"Read\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$siem_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Write_Bytes_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$siem_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Handle Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Handle_Count\") as \"Handle Count\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$siem_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO op/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Write_Operations_persec\") AS \"Read\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$siem_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Read_Operations_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$siem_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "OTHER SERVICES UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($interval), instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"Working_Set_-_Private\") FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($interval), instance fill(none)",
     "select": [
      [
       { "params": [ "Working_Set_-_Private" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mpx-stability-aio" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "PT.MaxPatrol.Topology.Host" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO bytes/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Read_Bytes_persec\") AS \"Read\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Write_Bytes_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO op/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Write_Operations_persec\") AS \"Read\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col:$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"IO_Read_Operations_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Handle Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Handle_Count\") as \"Handle Count\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}