{
 "title": "Telegraf_MPXSIEM_LIN",
 "tags": [ "telegraf" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "HostName",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE system = 'linux'"
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "SHOW TAG VALUES WITH KEY=interface WHERE host =~ /$host/"
   }
  ]
 },
 "panels": [
  { "title": "INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$host$/",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE  \"host\" =~ /^$host$/\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Kernels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"n_cpus\") FROM \"system\" WHERE  \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"available_percent\") FROM \"mem\" WHERE  \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk space /",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"free\") AS \"value\" FROM \"disk\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Network Mb/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT  non_negative_derivative(mean(\"bytes_recv\"), 1s) *8 AS \"Bytes recv\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"Bytes sent\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "testcase", "operator": "=~", "value": "/^$testcase$/" },
      { "condition": "AND", "key": "testrun", "operator": "=~", "value": "/^$testrun$/" },
      { "condition": "AND", "key": "testsuite", "operator": "=~", "value": "/^$testsuite$/" },
      { "condition": "AND", "key": "PT_project", "operator": "=~", "value": "/^$pt_project$/" },
      { "condition": "AND", "key": "interface", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Network pps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(packets_recv),1s) AS \"in_pps\", non_negative_derivative(mean(packets_sent),1s) AS \"out_pps\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "testcase", "operator": "=~", "value": "/^$testcase$/" },
      { "condition": "AND", "key": "testrun", "operator": "=~", "value": "/^$testrun$/" },
      { "condition": "AND", "key": "testsuite", "operator": "=~", "value": "/^$testsuite$/" },
      { "condition": "AND", "key": "PT_project", "operator": "=~", "value": "/^$pt_project$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netstat",
     "query": "SELECT mean(*) FROM \"netstat\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "testcase", "operator": "=~", "value": "/^$testcase$/" },
      { "condition": "AND", "key": "testrun", "operator": "=~", "value": "/^$testrun$/" },
      { "condition": "AND", "key": "testsuite", "operator": "=~", "value": "/^$testsuite$/" },
      { "condition": "AND", "key": "PT_project", "operator": "=~", "value": "/^$pt_project$/" }
     ]
    }
   ]
  },
  {
   "title": "Total NET bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT mean(bytes_recv) AS \"Bytes recv\", mean(bytes_sent) AS \"Bytes send\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "testcase", "operator": "=~", "value": "/^$testcase$/" },
      { "condition": "AND", "key": "testrun", "operator": "=~", "value": "/^$testrun$/" },
      { "condition": "AND", "key": "testsuite", "operator": "=~", "value": "/^$testsuite$/" },
      { "condition": "AND", "key": "PT_project", "operator": "=~", "value": "/^$pt_project$/" },
      { "condition": "AND", "key": "interface", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  { "title": "MPX SIEM SERVICES UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage SIEM",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ptnad_procstat",
     "query": "SELECT last(/.*_cpu_usage/) FROM \"mpx_procstat\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ ".*_cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "testcase", "operator": "=~", "value": "/^$testcase$/" },
      { "condition": "AND", "key": "PT_project", "operator": "=~", "value": "/^$pt_project$/" },
      { "condition": "AND", "key": "testrun", "operator": "=~", "value": "/^$testrun$/" },
      { "condition": "AND", "key": "testsuite", "operator": "=~", "value": "/^$testsuite$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage SIEM",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(/.*_memory_rss$/) FROM \"mpx_procstat\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process num threads SIEM",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(/.*_num_threads/) FROM \"mpx_procstat\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SERVER UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(*) FROM \"mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SwapUsage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(total) AS \"Total swap\" FROM \"swap\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(used) AS \"Used swap\" FROM \"swap\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk R/W bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /sda|sdb$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "(v|s)d(a|b|c|d)$/" }
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /sdb|sda$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "(v|s)d(a|b|c|d)$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "query": "SELECT last(\"iops_in_progress\") AS \"iops in progress\"  FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" = 'sda' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "diskio",
     "query": "SELECT last(\"iops_in_progress\") AS \"iops in progress\"  FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" = 'sdb' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read_time\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write_time\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(io_time),1s) as \"io_time\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"total\") AS \"total\", last(\"used\") AS \"used\", last(\"free\") AS \"free\" FROM \"disk\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY path,  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"sda_read\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /sda/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"sda_write\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /sda/  AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"sdb_read\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /sdb/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"sdb_write\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /sdb/  AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "Disk await",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "await sda",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"await\") FROM \"disk\" WHERE \"host\" =~ /^$host$/ AND \"device\" = 'sda' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "await" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "sda" }
     ]
    },
    {
     "alias": "await sdb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"await\") FROM \"disk\" WHERE \"host\" =~ /^$host$/ AND \"device\" = 'sdb' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "await" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "% Util DISK IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "% Util sda",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"pct_util\") FROM \"disk\" WHERE \"device\" = 'sda' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "sda" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "% Util sdb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"pct_util\") FROM \"disk\" WHERE \"device\" = 'sdb' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "sdb" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}