{
 "title": "Telegraf_PostgreSQL_Lags",
 "description": "virt-stability - copy PTLAB data",
 "tags": [ "ptlab" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" "
   },
   { "name": "DataSource", "label": "DataSource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "CURRENT LAG",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Assets identification" }
     ]
    }
   ]
  },
  {
   "title": "LAG  HISTORY: Assets identification",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Assets identification" }
     ]
    }
   ]
  },
  {
   "title": "CURRENT LAG",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "dashboard",
       "operator": "=",
       "value": "Assets processing buffer filling"
      }
     ]
    }
   ]
  },
  {
   "title": "LAG Assets processing buffer filling",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "dashboard",
       "operator": "=",
       "value": "Assets processing buffer filling"
      }
     ]
    }
   ]
  },
  {
   "title": "CURRENT LAG",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Dynamic groups processing" }
     ]
    }
   ]
  },
  {
   "title": "LAG HISTORY: Dynamic groups processing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Dynamic groups processing" }
     ]
    }
   ]
  },
  {
   "title": "ASSETS IDENTIFICATION",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": {
    "content": "\n`value`: MP_Assets_Identification: select Value FROM \"Checkpoints\" WHERE Id = 2\\\n`lag`:   MP_Assets_Scans: select count(*) from asset_scans where orderedid>{value}\n\n\n\n"
   },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "ASSETS PROCESSING BUFFER FILLING",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "options": {
    "content": "`value1`:  maxpatrol_assets_processing: select Value from checkpoints WHERE Id = 'IdentificationService'\\\n`value2`:  MP_Assets_Identification: select max(checkpoint) from commits where streamtype in ('ScopeKeySet', 'IdentityRemoveProcessManager','IdentityExpirationProcessManager')\\\n`lag`: as diff"
   },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "DYNAMIC GROUPS PROCESSING",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": {
    "content": "\n`value`:  maxpatrol_assets_processing: select Value from checkpoints WHERE Id = 'GroupsService'\\\n`lag`:  maxpatrol_assets_processing: select count(*) from commits where streamtype in('Asset', 'AssetInputProcessManager', 'AssetsGroupsRelocationProcessManager', 'AssetsRemoveProcessManager', 'Group', 'Scope') and checkpoint>{value}\n\n\n\n"
   },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "CURRENT LAG",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 9 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Scan enrichment" }
     ]
    }
   ]
  },
  {
   "title": "LAG HISTORY: Scan enrichment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Scan enrichment" }
     ]
    }
   ]
  },
  {
   "title": "CURRENT LAG",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 9 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Temporal readmodel processing" }
     ]
    }
   ]
  },
  {
   "title": "LAG HISTORY: Temporal readmodel processing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Temporal readmodel processing" }
     ]
    }
   ]
  },
  {
   "title": "CURRENT LAG",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 9 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "dashboard",
       "operator": "=",
       "value": "Assets processing buffer processing"
      }
     ]
    }
   ]
  },
  {
   "title": "[R24] LAG HISTORY: Assets processing buffer processing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "lag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "dashboard",
       "operator": "=",
       "value": "Assets processing buffer processing"
      }
     ]
    }
   ]
  },
  {
   "title": "SCAN ENRICHMENT",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "options": {
    "content": "\n`value`:  MP_Assets_Scans: select max(orderedid) from asset_scans\\\n`lag`:  MP_Assets_Scans: select count(*) from asset_raw_scans where orderedid>{value}\n\n\n\n"
   },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "TEMPORAL READMODEL PROCESSING ",
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "options": {
    "content": "\n`value`:  maxpatrol_assets_temporal_rm: select Value from checkpoints WHERE Id = 'AssetsEventProcessingService'\\\n`lag`:  maxpatrol_assets_processing: select count(*) from commits where streamtype in('Asset, 'AssetInputProcessManager', 'VulnerableAsset', 'AssetsRemoveProcessManager', 'Group', 'Scope', 'GroupAsset', 'AssetsPassportUpdateProcessManager', 'AssetsGroupsRelocationProcessManager', 'GroupOperationProcessManager, 'Tag', 'VulnerabilityOperationProcessManager', 'TagRemoveProcessManager') and checkpoint>{value}\n\n\n\n"
   },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "[R24] ASSETS PROCESSING BUFFER PROCESSING",
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "options": {
    "content": "\n`lag`:  maxpatrol_assets_processing: select count(distinct(identity_checkpoint)) from __asset_identity_events\n\n\n\n"
   },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "VALUE Assets identification",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Assets identification" }
     ]
    }
   ]
  },
  {
   "title": "VALUE Assets processing buffer filling",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "alias": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "dashboard",
       "operator": "=",
       "value": "Assets processing buffer filling"
      }
     ]
    }
   ]
  },
  {
   "title": "VALUE Dynamic groups processing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "alias": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Dynamic groups processing" }
     ]
    }
   ]
  },
  {
   "title": "VALUE Scan Enrichment",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Scan enrichment" }
     ]
    }
   ]
  },
  {
   "title": "VALUE Temporal readmodel processing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "alias": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "Temporal readmodel processing" }
     ]
    }
   ]
  },
  {
   "title": "LG Assets processing buffer processing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "alias": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "dashboard",
       "operator": "=",
       "value": "Assets processing buffer processing"
      }
     ]
    }
   ]
  },
  {
   "title": "ERRORS: Control collect script errors in working",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"MP_Assets_Scans: select max(orderedid) from asset_raw_scans\") FROM \"pgsql\" WHERE (\"dashboard\" = 'Scan enrichment' AND \"host\" = 'mpx-stability-core') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dashboard", "operator": "=", "value": "errors" }
     ]
    }
   ]
  }
 ]
}