{
 "title": "AGENTS",
 "description": "agent",
 "tags": [ "siem-mon" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "win agent",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE (agent = 'on'  AND osname = 'windows')"
   },
   {
    "name": "nix_host",
    "label": "nix agent",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE (agent = 'on'  AND  osname = 'linux')"
   }
  ]
 },
 "panels": [
  { "title": "win agent $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "interrupt" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host: Agent cahe ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "private",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dir_path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dirsize",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dir_size_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "dir_path", "operator": "=~", "value": "/(private)/" }
     ]
    }
   ]
  },
  {
   "title": "network packets per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT non_negative_derivative(mean(packets_recv),1s) AS \"in_pps\", non_negative_derivative(mean(packets_sent),1s) AS \"out_pps\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "Packets_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT non_negative_derivative(mean(packets_recv),1s) AS \"in_pps\", non_negative_derivative(mean(packets_sent),1s) AS \"out_pps\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "Packets_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host: CPU usage by ModuleHost*  processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "private",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/(ModuleHost*)/" }
     ]
    }
   ]
  },
  {
   "title": "$host: MEM usage by ModuleHost*  processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "private",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Working_Set_-_Private" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/(ModuleHost*)/" }
     ]
    }
   ]
  },
  {
   "title": " $host: MEM Avail ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "memory available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(/.*_memory_rss$/) FROM \"mpx_procstat\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "network bytes per second",
   "type": "graph",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT non_negative_derivative(mean(packets_recv),1s) AS \"in_pps\", non_negative_derivative(mean(packets_sent),1s) AS \"out_pps\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT non_negative_derivative(mean(packets_recv),1s) AS \"in_pps\", non_negative_derivative(mean(packets_sent),1s) AS \"out_pps\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT (\"Free_Megabytes\" + \"Percent_Free_Space\") FROM \"win_disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"total\")-last(\"used\") AS \"fres\" FROM \"disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total-used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "fres" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Util DISK IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"pct_util\") FROM \"disk\" WHERE \"device\" = 'sda' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ReadBytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "WriteBytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/([A-Z]:)/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"await\") FROM \"disk\" WHERE \"host\" =~ /^$host$/ AND \"device\" = 'sda' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Avg._Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "nix agent $nix_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "pct_user" ], "type": "alias" }
      ],
      [
       { "params": [ "pct_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "pct_system" ], "type": "alias" }
      ],
      [
       { "params": [ "pct_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*(-1)+100" ], "type": "math" },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" }
     ]
    }
   ]
  },
  {
   "title": "$nix_host: Agent cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "data",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dir_path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dirsize",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dir_size_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" },
      { "condition": "AND", "key": "dir_path", "operator": "=~", "value": "/(data)/" }
     ]
    }
   ]
  },
  {
   "title": "network packets sent",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 26 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(packets_recv),1s) AS \"in_pps\", non_negative_derivative(mean(packets_sent),1s) AS \"out_pps\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/(ens.*|eth.*)/" }
     ]
    },
    {
     "alias": "$tag_interface recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(packets_recv),1s) AS \"in_pps\", non_negative_derivative(mean(packets_sent),1s) AS \"out_pps\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/(ens.*|eth.*)/" }
     ]
    }
   ]
  },
  {
   "title": "$nix_host: MEM avail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(/.*_memory_rss$/) FROM \"mpx_procstat\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" }
     ]
    }
   ]
  },
  {
   "title": "$nix_host: CPU usage by Agent process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mpx_procstat",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cpu usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "Agent" }
     ]
    }
   ]
  },
  {
   "title": "$nix_host: CPU usage by Agent process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mpx_procstat",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cpu usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "Agent" }
     ]
    }
   ]
  },
  {
   "title": "network bytes sent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(packets_recv),1s) AS \"in_pps\", non_negative_derivative(mean(packets_sent),1s) AS \"out_pps\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/(ens.*|eth.*)/" }
     ]
    },
    {
     "alias": "$tag_interface recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(packets_recv),1s) AS \"in_pps\", non_negative_derivative(mean(packets_sent),1s) AS \"out_pps\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND \"interface\" =~ /^$interface$/ AND \"interface\" != 'all' AND $timeFilter GROUP BY time($__interval), interface",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/ens.*/" }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT (\"Free_Megabytes\" + \"Percent_Free_Space\") FROM \"win_disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" }
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"total\")-last(\"used\") AS \"fres\" FROM \"disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" }
     ]
    }
   ]
  },
  {
   "title": "$nix_host: DISK util IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$col $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"wkB_per_s\")  * 1024 AS \"write (b/s)\", mean(\"rkB_per_s\")  * 1024 AS \"read (b/s)\" FROM \"disk\" WHERE (\"host\" =~ /^$host$/ AND \"device\" = 'sda') AND $timeFilter GROUP BY time($__interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "wkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write" ], "type": "alias" }
      ],
      [
       { "params": [ "rkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/(sd[a-z])/" }
     ]
    }
   ]
  },
  {
   "title": "$nix_host: DISK queue legth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "aqu-sz" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue length" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/(sd[a-z])/" }
     ]
    }
   ]
  },
  {
   "title": "$nix_host: UDP (drops/min) count on local port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "port: $tag_local_port",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "local_port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "udp_stat",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "drops_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$nix_host$/" }
     ]
    }
   ]
  }
 ]
}