{
 "title": "CORE server",
 "description": "Windows host dashboard for telegraf metrics pumped into influxdb",
 "tags": [ "siem-mon" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE core = 'on' "
   },
   {
    "name": "mpx_process",
    "label": "mpx_process",
    "query": "SHOW TAG VALUES FROM \"win_proc\" WITH KEY = \"instance\""
   },
   {
    "name": "other_process",
    "label": "other_process",
    "query": "SHOW TAG VALUES FROM \"win_proc\" WITH KEY = \"instance\""
   },
   { "name": "win_cpu_num", "label": "win_cpu", "query": "36" }
  ]
 },
 "panels": [
  {
   "title": "Load mem&proc",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "proc",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Free_Space\") *-1+100 FROM \"win_disk\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^[C-Z]:$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "mem",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"Percent_Free_Space\") *-1+100 FROM \"win_disk\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^[C-Z]:$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*(-1)+ 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "pct_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*(-1)+100" ], "type": "math" },
       { "params": [ "cpu load" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Percent_Free_Space\") *-1+100 FROM \"win_disk\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^[C-Z]:$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^[C-Z]:/" }
     ]
    },
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/sd[a-z][0-9]/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT \"System_Up_Time\" FROM \"win_system\" WHERE \"host\" =~ /^$host$/ AND  $timeFilter",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT last(\"Threads\") FROM \"win_system\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "PG size of databases",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGdbsizes",
     "query": "SELECT last(\"size\") FROM \"PGdbsizes\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"dbname\" fill(none)",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Assets Processing lag history",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_dashboard",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dashboard" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"Percent_Privileged_Time\") AS \"% Priviledged Time\", last(\"Percent_User_Time\") AS \"% User Time\", last(\"Percent_Interrupt_Time\") AS \"% Interrupt Time\", last(\"Percent_Idle_Time\") AS \"% Idle Time\", last(\"Percent_Processor_Time\") AS \"% Processor Time\" FROM \"win_cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Assets Processing lag",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dashboard",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dashboard" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "query": "SELECT last(\"Percent_Privileged_Time\") AS \"% Priviledged Time\", last(\"Percent_User_Time\") AS \"% User Time\", last(\"Percent_Interrupt_Time\") AS \"% Interrupt Time\", last(\"Percent_Idle_Time\") AS \"% Idle Time\", last(\"Percent_Processor_Time\") AS \"% Processor Time\" FROM \"win_cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "SERVER UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT last(\"Percent_Privileged_Time\") AS \"% Priviledged Time\", last(\"Percent_User_Time\") AS \"% User Time\", last(\"Percent_Interrupt_Time\") AS \"% Interrupt Time\", last(\"Percent_Idle_Time\") AS \"% Idle Time\", last(\"Percent_Processor_Time\") AS \"% Processor Time\" FROM \"win_cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "% Priviledged Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "% Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "pct_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "% user" ], "type": "alias" }
      ],
      [
       { "params": [ "pct_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "% iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "pct_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*(-1)+100" ], "type": "math" },
       { "params": [ "% Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(\"Available_Bytes\") as \"Available Bytes\", last(\"Cache_Bytes\") as \"Cache Bytes\", last(\"Free_&_Zero_Page_List_Bytes\") as \"Free_&_Zero_Page_List_Bytes\" FROM \"win_mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "available" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "THREADS count total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "query": "SELECT last(\"Available_Bytes\") as \"Available Bytes\", last(\"Cache_Bytes\") as \"Cache Bytes\", last(\"Free_&_Zero_Page_List_Bytes\") as \"Free_&_Zero_Page_List_Bytes\" FROM \"win_mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "Disks Free%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"Percent_Free_Space\") AS \"% Free Space\" FROM \"win_disk\" WHERE \"instance\" =~ /^$disk/ AND \"host\" =~ /ptlab-mpx-core/ AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "free space" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^[C-Z]:/" }
     ]
    },
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*(-1)+ 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/sd[a-z][0-9]/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "SELECT last(\"Percent_Usage\") AS \"Swap percent usage\" FROM \"win_swap\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disks R/W Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"Disk_Read_Bytes_persec\") AS \"Disk_Read_Bytes_persec\", last(\"Disk_Write_Bytes_persec\") AS \"Disk_Write_Bytes_persec\" FROM \"win_disk\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($__interval), \"host\", instance fill(0)",
     "select": [
      [
       { "params": [ "Avg._Disk_Bytes/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write bytes/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_Bytes/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read bytes/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^[C-Z]:/" }
     ]
    },
    {
     "alias": "$col $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "wkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1024" ], "type": "math" },
       { "params": [ "write (b/s)" ], "type": "alias" }
      ],
      [
       { "params": [ "rkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1024" ], "type": "math" },
       { "params": [ "read (b/s)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "sda" }
     ]
    }
   ]
  },
  {
   "title": "Disk Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"Avg._Disk_Read_Queue_Length\") AS \"Avg._Disk_Read_Queue_Length\", last(\"Avg._Disk_Write_Queue_Length\") AS \"Avg._Disk_Write_Queue_Length\" FROM \"win_disk\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($__interval), \"host\", instance fill(0)",
     "select": [
      [
       { "params": [ "Avg._Disk_Read_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read queue length" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_Write_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write queue length" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/([A-Z]:)/" }
     ]
    },
    {
     "alias": "$col $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "aqu-sz" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "queue length" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk R/W IOps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"Disk_Reads_persec\") AS \"Disk_Reads_persec\", last(\"Disk_Writes_persec\") AS \"Disk_Writes_persec\" FROM \"win_disk\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($__interval), \"host\", instance fill(0)",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "reads" ], "type": "alias" }
      ],
      [
       { "params": [ "Disk_Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/([A-Z]:)/" }
     ]
    }
   ]
  },
  { "title": "MPX SERVICES UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT mean(\"Working_Set_-_Private\") FROM \"win_proc\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$mpx_process$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
     "select": [
      [
       { "params": [ "Working_Set_-_Private" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$mpx_process$/" }
     ]
    },
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "rss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE \"(\"host\" =~ /^$host$/ AND \"instance\" =~ /^$mpx_process$/)  AND $timeFilter GROUP BY time($__interval), instance fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / $win_cpu_num" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$mpx_process$/" }
     ]
    },
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "HANDLES count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE \"(\"host\" =~ /^$host$/ AND \"instance\" =~ /^$mpx_process$/)  AND $timeFilter GROUP BY time($__interval), instance fill(linear)",
     "select": [
      [
       { "params": [ "Handle_Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$mpx_process$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk read bytes/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"IO_Write_Bytes_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(0)",
     "select": [
      [
       { "params": [ "IO_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "read b/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$mpx_process$/" }
     ]
    },
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_read"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "read b/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk write bytes/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"IO_Write_Bytes_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(0)",
     "select": [
      [
       { "params": [ "IO_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write b/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$mpx_process$/" }
     ]
    },
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_write"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write b/s" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": ".NET CLR mem. Gen2 HS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_NET_C_MEM",
     "query": "SELECT mean(\"Working_Set_-_Private\") FROM \"win_proc\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$mpx_process$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
     "select": [
      [
       { "params": [ "Gen_2_heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$mpx_process$/" }
     ]
    }
   ]
  },
  {
   "title": ".NET CLR mem. Large object HS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_NET_C_MEM",
     "query": "SELECT mean(\"Working_Set_-_Private\") FROM \"win_proc\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$mpx_process$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
     "select": [
      [
       { "params": [ "Large_Object_Heap_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$mpx_process$/" }
     ]
    }
   ]
  },
  {
   "title": ".NET CLR mem. % time in GC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_NET_C_MEM",
     "query": "SELECT mean(\"Working_Set_-_Private\") FROM \"win_proc\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$mpx_process$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none)",
     "select": [
      [
       { "params": [ "Percent_Time_in_GC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$mpx_process$/" }
     ]
    }
   ]
  },
  { "title": "OTHER SERVICES UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Processor time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$other_process$/" }
     ]
    },
    {
     "alias": "Postgres * summary",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "% Postgres Processor time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/(postgres*)/" }
     ]
    },
    {
     "alias": "Java* summary",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "%java  Processor time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/(java*)/" }
     ]
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"Working_Set_-_Private\") FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(none)",
     "select": [
      [
       { "params": [ "Working_Set_-_Private" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mpx-stability-aio" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "PT.MaxPatrol.Topology.Host" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO bytes/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "read $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"IO_Write_Bytes_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(0)",
     "select": [
      [
       { "params": [ "IO_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$other_process$/" }
     ]
    },
    {
     "alias": "write $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"IO_Write_Bytes_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(0)",
     "select": [
      [
       { "params": [ "IO_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$other_process$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO op/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "write: $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"IO_Read_Operations_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(0)",
     "select": [
      [
       { "params": [ "IO_Write_Operations_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$other_process$/" }
     ]
    },
    {
     "alias": "read: $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"IO_Read_Operations_persec\") AS \"Write\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(0)",
     "select": [
      [
       { "params": [ "IO_Read_Operations_persec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$other_process$/" }
     ]
    }
   ]
  },
  {
   "title": "Handle Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_proc",
     "query": "SELECT last(\"Handle_Count\") as \"Handle Count\" FROM \"win_proc\" WHERE \"host\" =~ /^$host$/ AND instance =~ /$other_process$/ AND $timeFilter GROUP BY time($__interval), instance fill(0)",
     "select": [
      [
       { "params": [ "Thread_Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$other_process$/" }
     ]
    }
   ]
  },
  {
   "title": "NETWORK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$col $tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "query": "SELECT mean(\"Bytes_Received_persec\") *8 AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($__interval), \"host\", instance fill(linear)",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "received" ], "type": "alias" }
        ],
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "query": "SELECT mean(\"Packets_Received_persec\") AS \"Packets Received / sec\", mean(\"Packets_Sent_persec\") AS \"Packets Sent / sec\" FROM \"win_net\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /$network$/ AND $timeFilter GROUP BY time($__interval), \"host\", instance fill(linear)",
       "select": [
        [
         { "params": [ "Packets_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "received" ], "type": "alias" }
        ],
        [
         { "params": [ "Packets_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "sent" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}