{
 "title": "POSTGRE SQL",
 "tags": [ "siem-mon" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE core='on'"
   }
  ]
 },
 "panels": [
  {
   "title": "PG Database size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGdbsizes",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "PG dead tuples",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGdeadtuples",
     "select": [
      [
       { "params": [ "dead_tuples" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "PG Assets count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_dbname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dbname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "select": [
      [
       { "params": [ "assest_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "PG Assets count changes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "diff",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PGstat",
     "select": [
      [
       { "params": [ "assest_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "PG connections ACTIVE",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity",
     "select": [
      [
       { "params": [ "state_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "state", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "PG connections total (numbackend)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_stat_database",
     "select": [
      [
       { "params": [ "numbackends" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "PG connections IDLE",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity",
     "select": [
      [
       { "params": [ "state_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "state", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "PG conections IDLE in transaction",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity",
     "select": [
      [
       { "params": [ "state_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "state", "operator": "=", "value": "idle in transaction" }
     ]
    }
   ]
  },
  {
   "title": "PG TOP longest AVG queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "$tag_query_2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query_2" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "avg_time_2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "PG TOP longest queries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_query",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "query" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "total_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}