{
 "title": "SIEM server",
 "tags": [ "siem-mon" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "HostName",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE (siem= 'on' )"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Percent_Free_Space\") *-1+100 FROM \"win_disk\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^[C-Z]:$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^[C-Z]:/" }
     ]
    },
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/sd[a-z][0-9]/" }
     ]
    }
   ]
  },
  {
   "title": "Load mem&proc",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "proc",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Free_Space\") *-1+100 FROM \"win_disk\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^[C-Z]:$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "mem",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"Percent_Free_Space\") *-1+100 FROM \"win_disk\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^[C-Z]:$/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*(-1)+ 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "pct_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*(-1)+100" ], "type": "math" },
       { "params": [ "cpu load" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT \"System_Up_Time\" FROM \"win_system\" WHERE \"host\" =~ /^$host$/ AND  $timeFilter",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT last(\"Threads\") FROM \"win_system\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  { "title": "SERVER UTILIZATION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "pct_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "pct_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "guest" ], "type": "alias" }
      ],
      [
       { "params": [ "pct_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*(-1)+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT last(/^.*usage.*$/) FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "interrupt" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk bytes r|w per sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read_time\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "wkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1024" ], "type": "math" },
       { "params": [ "write (b/s)" ], "type": "alias" }
      ],
      [
       { "params": [ "rkB_per_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1024" ], "type": "math" },
       { "params": [ "read (b/s)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "sda" }
     ]
    },
    {
     "alias": "$col $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read_time\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write (b/s)" ], "type": "alias" }
      ],
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read(b/s)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/([A-Z]:)/" }
     ]
    }
   ]
  },
  {
   "title": "Network Mb/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col $tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(\"bytes_recv\"), 1s) *8 AS \"Bytes recv\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"Bytes sent\" FROM \"net\"  WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "recieved" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "interface", "operator": "!=", "value": "all" }
     ]
    },
    {
     "alias": "$col $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT non_negative_derivative(mean(\"bytes_recv\"), 1s) *8 AS \"Bytes recv\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"Bytes sent\" FROM \"net\"  WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "recieved" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(*) FROM \"mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"await\") FROM \"disk\" WHERE \"host\" =~ /^$host$/ AND \"device\" = 'sda' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Avg._Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue length" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "grafana-mpx-core" }
     ]
    },
    {
     "alias": "$col $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"await\") FROM \"disk\" WHERE \"host\" =~ /^$host$/ AND \"device\" = 'sda' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "aqu-sz" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue length" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SwapUsage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "SELECT last(total) AS \"Total swap\" FROM \"swap\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "swap used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "MPX SIEM SERVICES UTILIZATION",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage SIEM",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_service_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "service_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siemserver_procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_systemd_unit",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "systemd_unit" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mpx_procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MEM Usage SIEM",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_systemd_unit",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "systemd_unit" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mpx_procstat",
       "select": [
        [
         { "params": [ "memory_rss" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_service_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "service_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siemserver_procstat",
       "select": [
        [
         { "params": [ "memory_rss" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "SIEM processes wirte (bytes/sec)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_name",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "service_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siemserver_procstat",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write bytes/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_systemd_unit",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "systemd_unit" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mpx_procstat",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "SIEM processes read(bytes/sec)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_service_name",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "service_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siemserver_procstat",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read bytes/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_systemd_unit",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "systemd_unit" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mpx_procstat",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}