{
 "title": "SIEM processing",
 "description": "data from siem stat, FPTA",
 "tags": [ "siem-mon" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE (siem= 'on' )"
   },
   {
    "name": "fpta_page",
    "label": "fpta_page",
    "query": "SHOW TAG VALUES WITH KEY = \"fpta_param\""
   }
  ]
 },
 "panels": [
  {
   "title": "Important RMQ queues",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      {
       "condition": "AND",
       "key": "queue",
       "operator": "=~",
       "value": "/(correlator|enricher|normalizer|storage|router|resolver)/"
      }
     ]
    },
    {
     "alias": "(core) $tag_queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "queue", "operator": "=~", "value": "/(receiver.incoming)/" }
     ]
    }
   ]
  },
  {
   "title": "RMQ SIEM messages",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RMQ messages",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "messages" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Correlator routed events",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_subsection",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subsection" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "siem_stat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "appname", "operator": "=", "value": "correlator" },
      { "condition": "AND", "key": "section", "operator": "=", "value": "routed_events" }
     ]
    }
   ]
  },
  {
   "title": "events flow EPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "siem_eps",
     "select": [
      [
       { "params": [ "raw_eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "raw" ], "type": "alias" }
      ],
      [
       { "params": [ "norm_eps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "norm" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Table lists",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "TABLES EnrichmentRule",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_tables",
       "select": [
        [
         { "params": [ "currentSize" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "fillType", "operator": "=~", "value": "/([Ee]nrichment[Rr]ule)/" }
       ]
      }
     ]
    },
    {
     "title": "TABLES CorrelationRule",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_tables",
       "select": [
        [
         { "params": [ "currentSize" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "fillType", "operator": "=~", "value": "/([Cc]orrelation[Rr]ule)/" }
       ]
      }
     ]
    },
    {
     "title": "TABLES Asset Grid",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_tables",
       "select": [
        [
         { "params": [ "currentSize" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "fillType", "operator": "=", "value": "assetGrid" }
       ]
      }
     ]
    },
    {
     "title": "TABLES Registry & CybsiGrid",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "reg $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_tables",
       "select": [
        [
         { "params": [ "currentSize" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "fillType", "operator": "=~", "value": "/(|[Rr]egistry)/" }
       ]
      },
      {
       "alias": "cybsi $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_tables",
       "select": [
        [
         { "params": [ "currentSize" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "fillType", "operator": "=~", "value": "/([Cc]ybsi[Gg]rid)/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "FPTA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "FPTA enricher.db page usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_fpta_param",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "fpta_param" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "fpta_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "fpta_param", "operator": "=~", "value": "/^$fpta_page$/" },
        { "condition": "AND", "key": "fpta_db", "operator": "=", "value": "fpta_enricher.db" }
       ]
      }
     ]
    },
    {
     "title": "FPTA enricher.db page usage (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_fpta_param",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "fpta_param" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "fpta_stat",
       "select": [
        [
         { "params": [ "percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        {
         "condition": "AND",
         "key": "fpta_param",
         "operator": "=~",
         "value": "/(Total|Backed|Allocated|Remained|Used|GC|Retained|Reclaimable|Available)/"
        },
        { "condition": "AND", "key": "fpta_db", "operator": "=", "value": "fpta_enricher.db" }
       ]
      }
     ]
    },
    {
     "title": "FPTA core.db page usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_fpta_param",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "fpta_param" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "fpta_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        {
         "condition": "AND",
         "key": "fpta_param",
         "operator": "=~",
         "value": "/(Total|Backed|Allocated|Remained|Used|GC|Retained|Reclaimable|Available)/"
        },
        { "condition": "AND", "key": "fpta_db", "operator": "=", "value": "core_db.db" }
       ]
      }
     ]
    },
    {
     "title": "FPTA core.db page usage (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_fpta_param",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "fpta_param" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "fpta_stat",
       "select": [
        [
         { "params": [ "percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        {
         "condition": "AND",
         "key": "fpta_param",
         "operator": "=~",
         "value": "/(Total|Backed|Allocated|Remained|Used|GC|Retained|Reclaimable|Available)/"
        },
        { "condition": "AND", "key": "fpta_db", "operator": "=", "value": "core_db.db" }
       ]
      }
     ]
    },
    {
     "title": "FPTA fpta_db.db page usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_fpta_param",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "fpta_param" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "fpta_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        {
         "condition": "AND",
         "key": "fpta_param",
         "operator": "=~",
         "value": "/(Total|Backed|Allocated|Remained|Used|GC|Retained|Reclaimable|Available)/"
        },
        { "condition": "AND", "key": "fpta_db", "operator": "=", "value": "fpta_db.db" }
       ]
      }
     ]
    },
    {
     "title": "FPTA fpta_db.db page usage (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_fpta_param",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "fpta_param" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "fpta_stat",
       "select": [
        [
         { "params": [ "percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        {
         "condition": "AND",
         "key": "fpta_param",
         "operator": "=~",
         "value": "/(Total|Backed|Allocated|Remained|Used|GC|Retained|Reclaimable|Available)/"
        },
        { "condition": "AND", "key": "fpta_db", "operator": "=", "value": "fpta_db.db" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Enricher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Enricher query exec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "enricher" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "query_exec" }
       ]
      }
     ]
    },
    {
     "title": "Enricher query_full_scan",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "query": "SELECT mean(\"value\") FROM \"siem_stat\" WHERE (\"host\" =~ /^$host$/ AND \"appname\" = 'enricher' AND \"section\" = 'query_full_scans') AND $timeFilter GROUP BY time($__interval), \"subsection\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "enricher" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "query_full_scans" }
       ]
      }
     ]
    },
    {
     "title": "Enricher table inserts DIFF",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "enricher" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "table_inserts" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Router: Query full scans DIFF",
     "type": "graph",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "router" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "query_full_scans" }
       ]
      }
     ]
    },
    {
     "title": "Router:  events",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "router" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "events" }
       ]
      }
     ]
    },
    {
     "title": "Router: Query exec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "query": "SELECT first(\"counter\") FROM \"siem_metric_total\" WHERE (\"host\" =~ /^$host$/ AND \"group\" = 'query_exec' AND \"service\" = 'router') AND $timeFilter GROUP BY time(1m), \"name\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "router" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "query_exec" }
       ]
      }
     ]
    },
    {
     "title": "Router:  Query checked ranges",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "router" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "query_checked_ranges" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Correlator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of instances in memory by rule",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "correlator" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "instances_in_memory" }
       ]
      }
     ]
    },
    {
     "title": "Correlator deferred_events",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "correlator" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "deferred_events" }
       ]
      }
     ]
    },
    {
     "title": "Correlator emit by rules",
     "type": "graph",
     "gridPos": { "h": 10, "w": 15, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "correlator" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "emit" }
       ]
      }
     ]
    },
    {
     "title": "Correlator  events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "correlator" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "events" }
       ]
      }
     ]
    },
    {
     "title": "Correlator table_inserts DIFF",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "correlator" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "table_inserts" }
       ]
      }
     ]
    },
    {
     "title": "Correlator query_exec",
     "type": "graph",
     "gridPos": { "h": 10, "w": 15, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "correlator" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "query_exec" }
       ]
      }
     ]
    },
    {
     "title": "Correlator routed events DIFF",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "correlator" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "routed_events" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Normalizer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Normalizer processing",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "normalizer" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "processing" }
       ]
      }
     ]
    },
    {
     "title": "Normalized input_id",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "normalizer" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "input_id" }
       ]
      }
     ]
    },
    {
     "title": "Not normalized input_id",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_subsection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "subsection" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "siem_stat",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "appname", "operator": "=", "value": "normalizer" },
        { "condition": "AND", "key": "section", "operator": "=", "value": "input_id_not_normalized" }
       ]
      }
     ]
    }
   ]
  }
 ]
}